### ISSUE TITLE
Find and fix broken links

### ISSUE THREAD

**Issue by unseen1980** [unseen1980/free-it-books#1]
This is straightforward, just go through the links and remove or update any broken.

**Comment by romdim** [comment]
Can I work on this?

**Comment by georgioupanayiotis** [comment]
> This is straightforward, just go through the links and remove or update any broken.

Tried to open PR with name BrokenLinks but it says  has no upstream branch. 
@unseen1980 Please advice..

**Comment by georgioupanayiotis** [comment]
@unseen1980 just  opened the PR please at the `hacktoberfest` on my PR.
Thanks,
P.

**Comment by praveenscience** [comment]
@unseen1980 Taking this up. Have fixed a few and added some nice resources too... Will try to keep on updating. There are more than 2000 links that needs to be checked. Just checked with about 400. 😃

**Comment by praveenscience** [comment]
@unseen1980 Do you really wanna start merging PRs?
